services:
  user-backend:
    build:
      context: ./backend
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - galera-network

  ml-service:
    build:
      context: ./ml-service
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - galera-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  client:
    build:
      context: ./frontend/ReactClient
    ports:
      - 127.0.0.1:5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - galera-network
    volumes:
      - ./frontend/ReactClient:/app
      - /app/node_modules
  # telegram-bot:
  #   build:
  #     context: ./bot
  #   ports:
  #     - 127.0.0.1:9000:9000
  #   networks:
  #     - galera-network

networks:
  galera-network:
    driver: bridge