services:
  postgres:
    image: postgres:17
    networks:
      - cloud-removal
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  minio:
    image: quay.io/minio/minio
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    networks:
      - cloud-removal
    volumes:
      - buckets:/mnt
    command: server /mnt --console-address ":9001"
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD

  api:
    depends_on:
      - postgres
      - minio
    build:
      context: backend
      dockerfile: api/Dockerfile
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - cloud-removal
    environment:
      - CLOUD_REMOVAL_DATABASE_URL
      - CLOUD_REMOVAL_S3_PUBLIC_URL
      - CLOUD_REMOVAL_S3_URL
      - CLOUD_REMOVAL_S3_REGION
      - CLOUD_REMOVAL_S3_ACCESS_KEY
      - CLOUD_REMOVAL_S3_SECRET_KEY
      - CLOUD_REMOVAL_S3_BUCKET
      - CLOUD_REMOVAL_JWT_SECRET
      - CLOUD_REMOVAL_JWT_ALGORITHM
      - SENTINEL_CLIENT_ID
      - SENTINEL_CLIENT_SECRET

  ml:
    build:
      context: backend
      dockerfile: ml/Dockerfile
    ports:
      - 127.0.0.1:8100:8100
    networks:
      - cloud-removal
    volumes:
      - models:/models
    environment:
      - CLOUD_REMOVAL_DATABASE_URL
      - CLOUD_REMOVAL_S3_PUBLIC_URL
      - CLOUD_REMOVAL_S3_URL
      - CLOUD_REMOVAL_S3_REGION
      - CLOUD_REMOVAL_S3_ACCESS_KEY
      - CLOUD_REMOVAL_S3_SECRET_KEY
      - CLOUD_REMOVAL_S3_BUCKET
      - CLOUD_REMOVAL_JWT_SECRET
      - CLOUD_REMOVAL_JWT_ALGORITHM
      - CLOUD_REMOVAL_ENABLE_UPSCALING
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  client:
    build:
      context: ./frontend/ReactClient
    ports:
      - 127.0.0.1:5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - cloud-removal
    volumes:
      - ./frontend/ReactClient:/app
      - /app/node_modules

  # telegram-bot:
  #   build:
  #     context: ./bot
  #   ports:
  #     - 127.0.0.1:9000:9000
  #   networks:
  #     - cloud-removal

volumes:
  database:
  buckets:
  models:

networks:
  cloud-removal:
    driver: bridge
